### PR TITLE
Abstract configurable values to gradle.properties

### PR DESCRIPTION
**Pull request by flamendless**

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
https://github.com/love2d/love-android/actions/runs/4072979689/jobs/7016399946#step:4:4575

> Attribute `meta-data#com.google.android.gms.ads.APPLICATION_ID@value` at AndroidManifest.xml:42:9-42 requires a placeholder substitution but no value for `<APPLICATION_ID>` is provided.

Looks like `applicationId` can't be variable afterall?

**Comment by BrandonBlankerLim-it** [comment]
Hmm it seems I need to remove that ads usage

**Comment by flamendless** [comment]
@MikuAuahDark I've pushed the fix.

**Comment by MikuAuahDark** [comment]
Thanks. Merged.

**Comment by flamendless** [comment]
Fix https://github.com/love2d/love-android/pull/244

**Pull request merged**
